import {newProject,validateUnified,convertLegacy,EMPTY} from './unified-model.mjs';
import {isACS,editorStyle,imageStyle,nativeImageScale,pngWithDpi} from './drawing-style.mjs';
import {sanitizeSvg,svgDimensions,exportSvg as pageSvg} from './scene.mjs';
import {prepareChemDraw,summarizeImport} from './chemdraw-import.mjs';
import {normalizeMergedAromaticRings} from './ket-normalize.mjs';
import {initCanvasAgent} from './agent-ui.mjs';
import {initI18n,t} from './i18n.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],frame=$('#ketcher-frame');
let engine,busy=false,suppress=0,timer,toastTimer,writeQueue=Promise.resolve(),readQueue=Promise.resolve(),importFile,importPreview,programmaticUntil=0;
let docs=[],activeId=null,minimized=new Set(),engineDocId=null,project=null;
const clone=v=>structuredClone(v),encode=v=>JSON.stringify(v),different=(a,b)=>encode(a)!==encode(b);
function projectData(d){const p={version:2,format:'chemistry-lab',name:d.name,drawingStyle:d.drawingStyle,page:clone(d.page),ket:d.ket,highlights:clone(d.highlights||[])};if(d.originalProject)p.originalProject=clone(d.originalProject);return p;}
function signature(d){return encode(projectData(d));}
function makeDoc(input,extra={}){const p=input.version===1?convertLegacy(input):validateUnified(input);return {...p,originalProject:p.originalProject||null,id:extra.id||crypto.randomUUID(),savedSig:extra.savedSig||'',history:[],future:[]};}
function blankDoc(name='Untitled Drawing',style='standard',extra={}){const p=newProject(style);p.name=name;p.ket=EMPTY;return makeDoc(p,extra);}
function assignProject(d,p){d.version=p.version;d.format=p.format;d.name=p.name;d.drawingStyle=p.drawingStyle;d.page=clone(p.page);d.ket=p.ket;d.highlights=clone(p.highlights||[]);d.originalProject=p.originalProject||null;}
function pushHistory(d,before=projectData(d)){d.history.push(clone(before));if(d.history.length>40)d.history.shift();d.future=[];}
function uniqueName(base){const names=new Set(docs.map(d=>d.name));if(!names.has(base))return base;let i=2;while(names.has(`${base} (${i})`))i++;return `${base} (${i})`;}
function uniqueRename(base,id){const names=new Set(docs.filter(d=>d.id!==id).map(d=>d.name));if(!names.has(base))return base;let i=2;while(names.has(`${base} (${i})`))i++;return `${base} (${i})`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),6000);}
function error(e){console.error(e);toast(e.message||String(e));}
async function work(message,fn){if(busy)return;busy=true;$('#busy-text').textContent=message;$('#busy-overlay').classList.remove('hidden');try{return await fn();}catch(e){error(e);}finally{busy=false;$('#busy-overlay').classList.add('hidden');}}
const helpItems=['在主画布直接绘制、选择和移动原子、键、文字与箭头。','顶部集中放置新建、打开、保存、撤销、样式和窗口操作。','底部窗口条可切换、还原、关闭画布，点击铅笔可直接重命名。','ACS 1996 兼容样式下可拖动单个原子，调整局部键长和键角以疏开拥挤结构。','选择原子或键后点击「配色」，可使用预设色或系统取色器。','框选后可按 Ctrl+C、Ctrl+V；副本放在空白处并保持整体选中，点击画布后取消。','Agent 可以直接回答问题；需要改动画布时，只有点击「批准并应用」后才执行。','Ctrl+S 保存当前画布，编辑内容会自动写入恢复副本。'];$('#help-dialog ol').replaceChildren(...helpItems.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));$('#help-dialog ol + p').textContent='导入或 Agent 修改后，请检查价态、立体化学、配位键和机理箭头。';
const topbar=$('.topbar'),fileGroup=document.createElement('div'),styleGroup=document.createElement('div'),newButton=$('#new-project'),helpButton=$('#help');fileGroup.className='top-file-group';styleGroup.className='top-style-group';newButton.className='';newButton.textContent='＋ 新建';$('#undo').textContent='↶';$('#redo').textContent='↷';$('#style-details').textContent='ACS';helpButton.textContent='?';helpButton.title='操作说明与第三方许可';fileGroup.append(newButton,$('#open-project'),$('#save-project'),$('#undo'),$('#redo'));styleGroup.append($('#drawing-style'),$('#style-summary'),$('#style-details'));$('.brand').after(fileGroup);$('.document-title').after(styleGroup);topbar.append(helpButton);$('.offline').remove();$('.brand small').remove();$('.style-toolbar').remove();$('.library').remove();document.body.classList.add('compact-layout');$('#tool-hint').textContent='';$('#smiles-input').placeholder='SMILES';
const canvasMenu=document.createElement('div');canvasMenu.id='canvas-context-menu';canvasMenu.className='canvas-context-menu hidden';canvasMenu.innerHTML='<button data-canvas-action="copy"><span>复制选中内容</span><kbd>Ctrl+C</kbd></button><button data-canvas-action="paste"><span>粘贴</span><kbd>Ctrl+V</kbd></button>';document.body.append(canvasMenu);
const highlightButton=document.createElement('button');highlightButton.id='highlight-colors';highlightButton.title='给选中的原子和键设置自定义高亮颜色';highlightButton.innerHTML='<i></i><span>配色</span>';$('#fit-content').after(highlightButton);
const highlightDialog=document.createElement('dialog');highlightDialog.id='highlight-dialog';highlightDialog.innerHTML='<form method="dialog"><button class="close-help" value="cancel">关闭</button><h2>自定义高亮配色</h2><p class="subtle">先在画布中选择原子或键，再从预设色或系统取色器选择颜色。配色会随项目保存。</p><div id="highlight-presets" class="highlight-presets"></div><label class="highlight-custom"><span>自定义颜色</span><input id="highlight-color" type="color" value="#7B2CBF"><code id="highlight-hex">#7B2CBF</code></label><p id="highlight-selection" class="subtle">尚未选择原子或键</p><div class="dialog-actions"><button id="highlight-clear" type="button">清除全部配色</button><button id="highlight-apply" type="button" class="primary">应用到选区</button></div></form>';document.body.append(highlightDialog);
const HIGHLIGHT_COLORS=['#FF4545','#FF8A34','#FFC857','#68D442','#22B573','#3ACACC','#3185FC','#4434FF','#7B2CBF','#D946EF','#EC4899','#9C9C9C','#000000','#8B5E3C','#0F766E','#1E3A8A'];
$('#highlight-presets').replaceChildren(...HIGHLIGHT_COLORS.map(color=>{const button=document.createElement('button');button.type='button';button.dataset.color=color;button.title=color;button.style.backgroundColor=color;return button;}));
function focusCanvasInput(){frame.contentWindow?.focus();frame.contentDocument?.querySelector('[data-cliparea]')?.focus();}
async function runCanvasShortcut(action){focusCanvasInput();await new Promise(requestAnimationFrame);await window.desktop.canvasShortcut(action);}
async function copyCanvasSelection(){
  if(!hasCanvasSelection())throw Error(t('没有可复制的选中内容','There is no selected content to copy'));
  const doc=frame.contentDocument,clipboardApi=frame.contentWindow?.navigator?.clipboard;
  const dropdown=doc?.querySelector('[data-testid="copy-button-dropdown-triangle"]');
  if(!dropdown||!clipboardApi)throw Error(t('画布复制命令当前不可用','The canvas copy command is currently unavailable'));
  const ownWriteText=Object.getOwnPropertyDescriptor(clipboardApi,'writeText');let captured='';
  try{
    Object.defineProperty(clipboardApi,'writeText',{configurable:true,value:async source=>{captured=String(source||'');}});
    dropdown.click();
    let button=null;
    for(let i=0;i<20&&!button;i++){await new Promise(resolve=>setTimeout(resolve,15));button=doc.querySelector('[data-testid="copy-ket-button"]');}
    if(!button||button.disabled)throw Error(t('画布复制命令当前不可用','The canvas copy command is currently unavailable'));
    button.click();
    for(let i=0;i<12&&!captured;i++)await new Promise(resolve=>setTimeout(resolve,20));
  }finally{
    if(ownWriteText)Object.defineProperty(clipboardApi,'writeText',ownWriteText);else delete clipboardApi.writeText;
  }
  if(!captured)throw Error(t('没有取得可编辑的复制内容','Could not obtain editable copied content'));
  await window.desktop.writeCanvasClipboard(captured);
}
let contextMenuRequest=0,pendingCanvasCopy=null;
function hasCanvasSelection(){const selection=engine?.editor?.selection?.()||{};return Object.values(selection).some(group=>ids(group).length);}
async function canPasteCanvas(){try{return (await window.desktop.readChemDrawClipboard()).kind!=='unavailable';}catch{return false;}}
function hideCanvasMenu(){canvasMenu.classList.add('hidden');}
function closeNativeContextMenu(){try{frame.contentDocument.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true,cancelable:true}));}catch{}}
function runContextAction(action,closeMenu=true){
  hideCanvasMenu();
  if(action==='copy'){
    const operation=copyCanvasSelection().then(()=>{if(closeMenu)closeNativeContextMenu();});
    pendingCanvasCopy=operation;
    operation.catch(error).finally(()=>{if(pendingCanvasCopy===operation)pendingCanvasCopy=null;});
  }else if(action==='paste'){
    if(closeMenu)closeNativeContextMenu();
    work(t('粘贴剪贴板内容…','Pasting clipboard content…'),async()=>{if(pendingCanvasCopy)await pendingCanvasCopy;return pasteCanvasClipboard();});
  }
}
function wireContextActions(root){if(root.dataset.structlnkWired)return;root.dataset.structlnkWired='1';root.addEventListener('pointerdown',event=>event.stopPropagation());root.addEventListener('click',event=>{const button=event.target.closest('[data-canvas-action]');if(!button||button.disabled)return;event.preventDefault();event.stopPropagation();runContextAction(button.dataset.canvasAction);});}
function updateContextActions(root){const copy=root.querySelector('[data-canvas-action="copy"]'),paste=root.querySelector('[data-canvas-action="paste"]');if(copy)copy.disabled=!hasCanvasSelection();if(paste){paste.disabled=true;canPasteCanvas().then(enabled=>{if(paste.isConnected)paste.disabled=!enabled;});}}
function nativeContextMenu(){return [...frame.contentDocument.querySelectorAll('[role="menu"]')].reverse().find(menu=>menu.getBoundingClientRect().width&&menu.getBoundingClientRect().height);}
function mergeNativeContextMenu(){const menu=nativeContextMenu();if(!menu)return false;hideCanvasMenu();let actions=menu.querySelector('[data-structlnk-context-actions]');if(!actions){const doc=menu.ownerDocument;actions=doc.createElement('div');actions.dataset.structlnkContextActions='1';actions.className='structlnk-context-actions';actions.innerHTML=`<button type="button" data-canvas-action="copy" data-testid="structlnk-copy"><span>${t('复制选中内容','Copy selection')}</span><kbd>Ctrl+C</kbd></button><button type="button" data-canvas-action="paste" data-testid="structlnk-paste"><span>${t('粘贴','Paste')}</span><kbd>Ctrl+V</kbd></button>`;menu.append(actions);wireContextActions(actions);}updateContextActions(actions);return true;}
function showCanvasMenu(event){
  const request=++contextMenuRequest,rect=frame.getBoundingClientRect(),x=Math.min(innerWidth-230,Math.max(8,rect.left+event.clientX)),y=Math.min(innerHeight-104,Math.max(8,rect.top+event.clientY));
  const openFallback=()=>{canvasMenu.style.left=x+'px';canvasMenu.style.top=y+'px';canvasMenu.classList.remove('hidden');wireContextActions(canvasMenu);updateContextActions(canvasMenu);};
  hideCanvasMenu();
  for(const delay of [0,24,60,120,220,360])setTimeout(()=>{if(request!==contextMenuRequest)return;if(mergeNativeContextMenu())return;if(delay===360)openFallback();},delay);
  setTimeout(()=>{if(request===contextMenuRequest&&canvasMenu.classList.contains('hidden')&&!nativeContextMenu())openFallback();},560);
}
document.addEventListener('pointerdown',event=>{if(!event.target.closest('#canvas-context-menu')){contextMenuRequest++;hideCanvasMenu();}},true);document.addEventListener('keydown',event=>{if(event.key==='Escape'){contextMenuRequest++;hideCanvasMenu();}},true);
function stats(p){const ket=JSON.parse(p.ket),count={molecules:0,atoms:0,bonds:0,texts:0,arrows:0};for(const n of ket.root.nodes){const v=n.$ref?ket[n.$ref]:n;if(v?.type==='molecule'){count.molecules++;count.atoms+=v.atoms?.length||0;count.bonds+=v.bonds?.length||0;}else if(v?.type==='text')count.texts++;else if(v?.type==='arrow')count.arrows++;}return count;}
async function renameDoc(id,value){const d=docs.find(item=>item.id===id);if(!d)return;if(d.id===activeId)await readChanges();const next=uniqueRename(String(value||'').trim().slice(0,200)||'Untitled Drawing',id);if(next===d.name){render();return;}pushHistory(d);d.name=next;render();await persist(d);await saveMeta();toast(t('画布已重命名','Canvas renamed'));}
function beginDockRename(d,el,name){if(el.classList.contains('renaming'))return;el.classList.add('renaming');el.title='';const input=document.createElement('input');input.className='doc-tile-rename';input.value=d.name;input.maxLength=200;input.setAttribute('aria-label',t('画布名称','Canvas name'));input.onclick=input.ondblclick=event=>event.stopPropagation();name.replaceWith(input);let done=false;const finish=save=>{if(done)return;done=true;if(save)work(t('重命名画布…','Renaming canvas…'),()=>renameDoc(d.id,input.value));else renderDock();};input.onkeydown=event=>{event.stopPropagation();if(event.key==='Enter'){event.preventDefault();finish(true);}else if(event.key==='Escape'){event.preventDefault();finish(false);}};input.onblur=()=>finish(true);requestAnimationFrame(()=>{input.focus();input.select();});}
function renderDock(){
  const tiles=$('#doc-dock-tiles');tiles.replaceChildren();
  for(const d of docs){
    const el=document.createElement('div');el.className='doc-tile'+(d.id===activeId?' active':'')+(minimized.has(d.id)?' minimized':'');
    el.title=d.id===activeId&&!minimized.has(d.id)?t('当前窗口','Current window'):minimized.has(d.id)?t('已最小化 · 点击还原','Minimized · click to restore'):t('点击切换到此窗口','Click to switch to this window');
    const activate=()=>{if(el.classList.contains('renaming'))return;if(d.id!==activeId||minimized.has(d.id))work(t('切换画布…','Switching canvas…'),()=>activateDoc(d.id));};
    const name=document.createElement('span');name.className='doc-tile-name';name.textContent=d.name;name.title=t('双击重命名','Double-click to rename');
    if(signature(d)!==d.savedSig){const dot=document.createElement('i');dot.className='doc-dirty';dot.title=t('有未保存修改','Unsaved changes');name.prepend(dot);}
    name.onclick=event=>{event.stopPropagation();clearTimeout(name._switchTimer);name._switchTimer=setTimeout(activate,240);};
    name.ondblclick=event=>{event.stopPropagation();clearTimeout(name._switchTimer);beginDockRename(d,el,name);};
    const edit=document.createElement('button');edit.className='doc-tile-edit';edit.textContent='✎';edit.title=t('重命名画布','Rename canvas');edit.onclick=event=>{event.stopPropagation();beginDockRename(d,el,name);};
    const close=document.createElement('button');close.className='doc-tile-close';close.textContent='×';close.title=t('关闭窗口','Close window');close.onclick=event=>{event.stopPropagation();work(t('关闭窗口…','Closing window…'),()=>closeDoc(d.id));};
    el.append(name,edit,close);el.onclick=activate;tiles.append(el);
  }
  $('#doc-dock').classList.toggle('hidden',!docs.length);
}
function render(){const p=project;$('#project-name').value=p?.name||'';$('#drawing-style').value=p?.drawingStyle||'standard';$('#drawing-style').title=p&&isACS(p)?t('使用选择工具拖动原子，可手动调整键长和键角','Use the selection tool to drag atoms and adjust bond lengths and angles'):'';document.title=(p?.name||'Structlnk')+' · Structlnk';$('#style-summary').textContent=p?(isACS(p)?t('默认键长 14.4 pt · 可拖动原子疏排','Default bond 14.4 pt · drag atoms to adjust geometry'):t('结构、文字与箭头在同一画布编辑','Edit structures, text, and arrows on one canvas')):'';$('[data-export="png"]').textContent=p&&isACS(p)?t('PNG · 透明 / 600 dpi','PNG · Transparent / 600 dpi'):t('PNG · 透明 / 3×','PNG · Transparent / 3×');$('[data-export="pdf"]').textContent=p&&isACS(p)?t('PDF · US Letter / 原尺寸','PDF · US Letter / actual size'):t('PDF · A4 横向','PDF · A4 landscape');$('#original-export').classList.toggle('hidden',!p?.originalProject);$('#undo').disabled=!p?.history.length;$('#redo').disabled=!p?.future.length;if(p){const c=stats(p);$('#object-count').textContent=t(`${c.atoms} 个原子 · ${c.bonds} 条键 · ${c.texts} 处文字 · ${c.arrows} 个箭头`,`${c.atoms} atoms · ${c.bonds} bonds · ${c.texts} texts · ${c.arrows} arrows`);$('#save-state').textContent=signature(p)===p.savedSig?t('已保存','Saved'):t('自动恢复 · Ctrl+S 保存','Auto-recovered · Ctrl+S to save');}else{$('#object-count').textContent='';$('#save-state').textContent=t('没有打开的窗口 · 点击底部窗口条还原','No open window · click a tab below to restore');}$('#doc-empty').classList.toggle('hidden',!!p);renderDock();}
const ready=new Promise((resolve,reject)=>{let elapsed=0;const interval=setInterval(()=>{engine=frame.contentWindow?.ketcher;if(engine){clearInterval(interval);resolve(engine);}else if((elapsed+=100)>90000){clearInterval(interval);reject(Error('主画布启动失败，请重新打开软件'));}},100);});
ready.then(()=>{frame.contentDocument.addEventListener('contextmenu',showCanvasMenu,true);frame.contentDocument.addEventListener('pointerdown',event=>{if(!event.target.closest('[data-structlnk-context-actions]')){contextMenuRequest++;hideCanvasMenu();}},true);frame.contentDocument.addEventListener('keydown',event=>{if(event.key==='Escape'){contextMenuRequest++;hideCanvasMenu();}},true);}).catch(()=>{});
ready.then(()=>{let attempts=0;const restore=()=>{if(project)applyHighlights(project.highlights,project);else if(attempts++<100)setTimeout(restore,25);};restore();}).catch(()=>{});
const settings=style=>engine.editor.setOptions(JSON.stringify(editorStyle(style||project?.drawingStyle||'standard')));
async function readChanges(){readQueue=readQueue.catch(()=>{}).then(async()=>{if(suppress||!engine||!project)return;let highlights=currentHighlights(),ket=await engine.getKet(),remember=performance.now()>=programmaticUntil,normalized=normalizeMergedAromaticRings(ket);if(normalized.fixes){suppress++;try{await engine.setMolecule(normalized.ket,{preserveCanvasPosition:true});settings();ket=await engine.getKet();applyHighlights(highlights);programmaticUntil=performance.now()+500;}finally{suppress--;}toast('已自动修正连接处的碳价态并隐藏碳标记');}if(ket!==project.ket||encode(highlights)!==encode(project.highlights||[])){if(remember)pushHistory(project);project.ket=ket;project.highlights=highlights;render();}});await readQueue;}
function persist(doc=project){if(!doc)return Promise.resolve();const text=JSON.stringify(projectData(doc));if(new TextEncoder().encode(text).length>40*1024*1024)throw Error('项目超过 40 MB，无法保存，请减少嵌图片或拆分内容');writeQueue=writeQueue.catch(()=>{}).then(()=>window.desktop.autosave(doc.id,text));return writeQueue.then(()=>{if(doc.id===activeId)render();});}
async function saveMeta(){try{await window.desktop.autosaveMeta(JSON.stringify({activeId,order:docs.map(d=>d.id),minimized:[...minimized]}));}catch{}}
async function syncActive(recover=true){clearTimeout(timer);timer=null;const current=project;await readChanges();if(recover&&current)await persist(current);}
function changed(){if(suppress||!project)return;$('#save-state').textContent='正在保存恢复副本…';clearTimeout(timer);const id=project.id;timer=setTimeout(()=>{timer=null;if(project?.id!==id)return;readChanges().then(()=>persist(project)).catch(error);},350);}
async function put(next,{remember=true,recovery=true}={}){if(!project)throw Error('没有打开的窗口，请先还原一个画布');await readChanges();next=next.version===1?convertLegacy(next):validateUnified(next);const normalized=normalizeMergedAromaticRings(next.ket);next.ket=JSON.stringify(JSON.parse(normalized.ket),null,2);const before=projectData(project),oldKet=project.ket;clearTimeout(timer);suppress++;try{await engine.setMolecule(next.ket,{preserveCanvasPosition:true});const loaded=await engine.getKet();if(JSON.parse(next.ket).root.nodes.length&&!JSON.parse(loaded).root.nodes.length)throw Error('内容未能载入主画布，原项目保留');next.ket=loaded;if(remember&&different(before,next))pushHistory(project,before);assignProject(project,next);settings();applyHighlights(project.highlights);engine.editor.zoomAccordingContent(engine.editor.struct());project.ket=await engine.getKet();programmaticUntil=performance.now()+500;render();}catch(e){await engine.setMolecule(oldKet,{preserveCanvasPosition:true});assignProject(project,before);settings();applyHighlights(project.highlights);throw e;}finally{suppress--;}if(recovery)await persist();if(normalized.fixes)toast('已修正项目中连接处的碳价态并隐藏碳标记');}
async function applyAgentSource(source,add=false){if(!project)throw Error('没有打开的窗口，请先还原一个画布');if(typeof source!=='string'||!source.trim()||source.length>200000)throw Error('Agent 返回的结构源无效');await readChanges();const before=projectData(project),oldKet=project.ket,oldHighlights=currentHighlights();clearTimeout(timer);timer=null;suppress++;try{if(add)await engine.addFragment(source.trim());else await engine.setMolecule(source.trim(),{preserveCanvasPosition:true});let ket=await engine.getKet();if(!JSON.parse(ket).root?.nodes?.length)throw Error('Agent 返回的结构无法载入画布');const normalized=normalizeMergedAromaticRings(ket);if(normalized.fixes){await engine.setMolecule(normalized.ket,{preserveCanvasPosition:true});ket=await engine.getKet();}if(ket===oldKet)throw Error('Agent 方案没有改变画布');pushHistory(project,before);project.ket=ket;project.highlights=add?oldHighlights:[];settings();applyHighlights(project.highlights);engine.editor.zoomAccordingContent(engine.editor.struct());project.ket=await engine.getKet();programmaticUntil=performance.now()+2000;render();}catch(e){await engine.setMolecule(oldKet,{preserveCanvasPosition:true});assignProject(project,before);settings();applyHighlights(project.highlights);throw e;}finally{suppress--;}await persist();}
function canvasBounds(struct=engine?.editor?.struct()){const points=[];for(const id of ids(struct?.atoms)){const p=struct.atoms.get(id)?.pp;if(Number.isFinite(p?.x)&&Number.isFinite(p?.y))points.push(p);}for(const id of ids(struct?.texts)){const text=struct.texts.get(id),p=text?.position||text?.pp;if(Number.isFinite(p?.x)&&Number.isFinite(p?.y))points.push(p);}for(const id of ids(struct?.rxnArrows)){const arrow=struct.rxnArrows.get(id);for(const p of arrow?.pos||[])if(Number.isFinite(p?.x)&&Number.isFinite(p?.y))points.push(p);}if(!points.length)return null;return {minX:Math.min(...points.map(p=>p.x)),maxX:Math.max(...points.map(p=>p.x)),minY:Math.min(...points.map(p=>p.y)),maxY:Math.max(...points.map(p=>p.y))};}
function agentBlankPoint(){const b=canvasBounds();return b?[Math.round((b.maxX+4)*100)/100,Math.round(((b.minY+b.maxY)/2)*100)/100]:[0,0];}
function agentTextKet(text){const content=JSON.stringify({blocks:[{key:'structlnk',text,type:'unstyled',depth:0,inlineStyleRanges:[],entityRanges:[],data:{}},{key:'end',text:'\u200b',type:'unstyled',depth:0,inlineStyleRanges:[],entityRanges:[],data:{}}],entityMap:{}}),width=Math.max(1.2,Math.min(12,text.length*.38)),height=.75;return JSON.stringify({root:{nodes:[{type:'text',data:{content,position:{x:0,y:0,z:0},pos:[{x:0,y:0,z:0},{x:0,y:-height,z:0},{x:width,y:-height,z:0},{x:width,y:0,z:0}]}}],connections:[],templates:[]}});}
function agentArrowKet(type,from,to){const modes={reaction:'open-angle',equilibrium:'equilibrium-open-angle',retrosynthetic:'retrosynthetic'},center=[(from[0]+to[0])/2,(from[1]+to[1])/2],a={x:from[0]-center[0],y:from[1]-center[1],z:0},b={x:to[0]-center[0],y:to[1]-center[1],z:0};return {ket:JSON.stringify({root:{nodes:[{type:'arrow',data:{mode:modes[type],pos:[a,b]}}],connections:[],templates:[]}}),center};}
function agentArrowPoints(arrow){if(Array.isArray(arrow?.pos)&&arrow.pos.length>=2)return arrow.pos;const out=[];if(arrow?.pos&&Number.isFinite(arrow.pos.x))out.push(arrow.pos);if(arrow?.pos2&&Number.isFinite(arrow.pos2.x))out.push(arrow.pos2);return out;}
function translatePoint(point,dx,dy){if(point&&Number.isFinite(point.x)&&Number.isFinite(point.y)){point.x+=dx;point.y+=dy;}}
function translateText(text,dx,dy){translatePoint(text?.position,dx,dy);for(const p of text?.pos||[])translatePoint(p,dx,dy);}
function translateArrow(arrow,dx,dy){for(const p of agentArrowPoints(arrow))translatePoint(p,dx,dy);}
function operationAtoms(struct,operation){const atomIds=new Set(operation.atomIds||[]);for(const id of operation.bondIds||[]){const bond=struct.bonds?.get(id);if(!bond)throw Error(`Agent 操作引用了不存在的键 ${id}`);atomIds.add(bond.begin);atomIds.add(bond.end);}return atomIds;}
function operationPoints(struct,operation){const atoms=operationAtoms(struct,operation),points=[];for(const id of atoms){const atom=struct.atoms?.get(id);if(!atom)throw Error(`Agent 操作引用了不存在的原子 ${id}`);points.push(atom.pp);}for(const id of operation.textIds||[]){const text=struct.texts?.get(id);if(!text)throw Error(`Agent 操作引用了不存在的文字 ${id}`);const p=text.position||text.pp;if(p)points.push(p);}for(const id of operation.arrowIds||[]){const arrow=struct.rxnArrows?.get(id);if(!arrow)throw Error(`Agent 操作引用了不存在的箭头 ${id}`);points.push(...agentArrowPoints(arrow));}return {atoms,points};}
function applyCanvasGeometry(struct,operation){
  if(operation.op==='set_atom'){const atom=struct.atoms?.get(operation.atomId);if(!atom)throw Error(`Agent 操作引用了不存在的原子 ${operation.atomId}`);if(operation.label!==null)atom.label=operation.label;if(operation.charge!==null)atom.charge=operation.charge;return;}
  if(operation.op==='set_bond'){const bond=struct.bonds?.get(operation.bondId);if(!bond)throw Error(`Agent 操作引用了不存在的键 ${operation.bondId}`);bond.type=operation.bondType;return;}
  if(!['move_objects','rotate_objects','align_objects'].includes(operation.op))return;
  const {atoms,points}=operationPoints(struct,operation);if(!points.length)throw Error('Agent 几何操作没有可移动的对象');
  if(operation.op==='move_objects'){for(const id of atoms)translatePoint(struct.atoms.get(id).pp,operation.dx,operation.dy);for(const id of operation.textIds)translateText(struct.texts.get(id),operation.dx,operation.dy);for(const id of operation.arrowIds)translateArrow(struct.rxnArrows.get(id),operation.dx,operation.dy);return;}
  if(operation.op==='rotate_objects'){const center=operation.center||[points.reduce((sum,p)=>sum+p.x,0)/points.length,points.reduce((sum,p)=>sum+p.y,0)/points.length],r=operation.angle*Math.PI/180,cos=Math.cos(r),sin=Math.sin(r),rotate=p=>{const x=p.x-center[0],y=p.y-center[1];p.x=center[0]+x*cos-y*sin;p.y=center[1]+x*sin+y*cos;};for(const id of atoms)rotate(struct.atoms.get(id).pp);for(const id of operation.textIds){const text=struct.texts.get(id);rotate(text.position);for(const p of text.pos||[])rotate(p);}for(const id of operation.arrowIds)for(const p of agentArrowPoints(struct.rxnArrows.get(id)))rotate(p);return;}
  const axis=operation.axis,target=operation.value===null?points.reduce((sum,p)=>sum+p[axis],0)/points.length:operation.value;for(const id of atoms)struct.atoms.get(id).pp[axis]=target;for(const id of operation.textIds){const text=struct.texts.get(id),anchor=text.position||text.pp,delta=target-anchor[axis];translateText(text,axis==='x'?delta:0,axis==='y'?delta:0);}for(const id of operation.arrowIds){const arrow=struct.rxnArrows.get(id),arrowPoints=agentArrowPoints(arrow),center=arrowPoints.reduce((sum,p)=>sum+p[axis],0)/arrowPoints.length,delta=target-center;translateArrow(arrow,axis==='x'?delta:0,axis==='y'?delta:0);}
}
async function applyAgentCanvasOperations(operations){if(!project||!Array.isArray(operations)||!operations.length||operations.length>20)throw Error('Agent 画布操作无效');await readChanges();const before=projectData(project),oldKet=project.ket,oldHighlights=currentHighlights(),oldStats=stats(project);clearTimeout(timer);timer=null;suppress++;try{for(const operation of operations){if(operation.op==='add_structure'){const at=operation.at||agentBlankPoint();await engine.addFragment(operation.source.trim(),{position:{x:at[0],y:at[1]}});}else if(operation.op==='add_text'){const at=operation.at||agentBlankPoint();await engine.addFragment(agentTextKet(operation.text),{position:{x:at[0],y:at[1]}});}else if(operation.op==='add_arrow'){const fallback=agentBlankPoint(),from=operation.from||[fallback[0]-1.5,fallback[1]],to=operation.to||[fallback[0]+1.5,fallback[1]],arrow=agentArrowKet(operation.arrowType,from,to);await engine.addFragment(arrow.ket,{position:{x:arrow.center[0],y:arrow.center[1]}});}}
    const geometry=operations.filter(operation=>!operation.op.startsWith('add_'));if(geometry.length){const struct=engine.editor.struct().clone();for(const operation of geometry)applyCanvasGeometry(struct,operation);engine.editor.struct(struct,false);}
    let ket=await engine.getKet(),normalized=normalizeMergedAromaticRings(ket);if(normalized.fixes){await engine.setMolecule(normalized.ket,{preserveCanvasPosition:true});ket=await engine.getKet();}if(ket===oldKet)throw Error('Agent 操作没有改变画布');const parsed=JSON.parse(ket);if(!Array.isArray(parsed.root?.nodes)||parsed.root.nodes.length>10000)throw Error('Agent 操作生成的画布结构无效');const added=operations.filter(x=>x.op==='add_structure').length,newStats=stats({...project,ket});if(added&&newStats.atoms<=oldStats.atoms)throw Error('Agent 添加的结构未通过结果检查');pushHistory(project,before);project.ket=ket;project.highlights=oldHighlights;settings();applyHighlights(project.highlights);engine.editor.zoomAccordingContent(engine.editor.struct());project.ket=await engine.getKet();programmaticUntil=performance.now()+2000;render();}catch(e){await engine.setMolecule(oldKet,{preserveCanvasPosition:true});assignProject(project,before);settings();applyHighlights(project.highlights);throw e;}finally{suppress--;}await persist();}
async function applyAgentPlan(plan){if(!plan||!['no_change','replace_source','add_source','replace_ket','canvas_ops','set_highlight','clear_highlight'].includes(plan.mode))throw Error('Agent 修改方案无效');if(plan.mode==='no_change')return;if(plan.mode==='replace_source')return applyAgentSource(plan.source);if(plan.mode==='add_source')return applyAgentSource(plan.source,true);if(plan.mode==='canvas_ops')return applyAgentCanvasOperations(plan.operations);if(['set_highlight','clear_highlight'].includes(plan.mode)){const target=agentHighlightTarget(plan.highlight);if(plan.mode==='set_highlight')return colorSelection(plan.highlight.color,target);if(plan.highlight.target==='all')return clearHighlights();return clearHighlightSelection(target);}if(typeof plan.ket!=='string'||new TextEncoder().encode(plan.ket).length>5_000_000)throw Error('Agent 返回的 KET 无效或过大');let ket;try{ket=JSON.parse(plan.ket);}catch{throw Error('Agent 返回的 KET 不是有效 JSON');}if(!Array.isArray(ket.root?.nodes)||ket.root.nodes.length>10000)throw Error('Agent 返回的 KET 结构无效');const next=projectData(project);next.ket=plan.ket;await put(next);}
function vec(v){return v&&Number.isFinite(v.x)&&Number.isFinite(v.y)?[Math.round(v.x*100)/100,Math.round(v.y*100)/100]:null;}
function ids(group){if(Array.isArray(group))return group;if(group?.keys)return [...group.keys()];if(group&&typeof group==='object')return Object.keys(group).map(Number);return [];}
function normalizeHighlights(value){return (Array.isArray(value)?value:[]).slice(0,500).map(item=>({atoms:[...new Set((item.atoms||[]).filter(Number.isInteger))],bonds:[...new Set((item.bonds||[]).filter(Number.isInteger))],color:/^#[0-9a-f]{6}$/i.test(item.color)?item.color.toUpperCase():'#000000'})).filter(item=>item.atoms.length||item.bonds.length);}
function currentHighlights(){try{return normalizeHighlights(engine?.editor?.highlights?.getAll?.().map(item=>item.highlight));}catch{return [];}}
function applyHighlights(value,doc=project){const list=normalizeHighlights(value),expected=encode(list),apply=()=>{suppress++;try{engine.editor.highlights.clear();if(list.length)engine.editor.highlights.create(...list);}finally{suppress--;}},restore=()=>{if(doc&&(project!==doc||encode(doc.highlights||[])!==expected))return;if(encode(currentHighlights())!==expected)apply();};apply();if(doc)doc.highlights=clone(list);if(list.length){requestAnimationFrame(restore);setTimeout(restore,60);setTimeout(restore,180);}return list;}
function highlightSelection(){const selection=engine?.editor?.selection?.(),atoms=ids(selection?.atoms),bonds=ids(selection?.bonds);return {atoms,bonds};}
function updateHighlightSelection(){const {atoms,bonds}=highlightSelection();$('#highlight-selection').textContent=atoms.length||bonds.length?t(`已选择 ${atoms.length} 个原子、${bonds.length} 条键`,`Selected: ${atoms.length} atoms, ${bonds.length} bonds`):t('尚未选择原子或键','No atoms or bonds selected');$('#highlight-apply').disabled=!project||!atoms.length&&!bonds.length;}
async function colorSelection(color,selection=highlightSelection()){if(!project)throw Error(t('没有打开的窗口','No window is open'));if(!/^#[0-9a-f]{6}$/i.test(color))throw Error(t('颜色值无效','Invalid color value'));const atoms=[...new Set(selection.atoms||[])],bonds=[...new Set(selection.bonds||[])];if(!atoms.length&&!bonds.length)throw Error(t('请先在画布中选择原子或键','Select atoms or bonds on the canvas first'));await readChanges();pushHistory(project);const atomSet=new Set(atoms),bondSet=new Set(bonds),keep=currentHighlights().map(item=>({...item,atoms:item.atoms.filter(id=>!atomSet.has(id)),bonds:item.bonds.filter(id=>!bondSet.has(id))})).filter(item=>item.atoms.length||item.bonds.length);keep.push({atoms,bonds,color:color.toUpperCase()});applyHighlights(keep);render();await persist();toast(t('已应用自定义高亮配色','Custom highlight color applied'));}
async function clearHighlights(){if(!project||!currentHighlights().length)return;await readChanges();pushHistory(project);applyHighlights([]);render();await persist();toast(t('已清除全部配色','All highlight colors cleared'));}
async function clearHighlightSelection(selection){if(!project)throw Error(t('没有打开的窗口','No window is open'));const atoms=[...new Set(selection.atoms||[])],bonds=[...new Set(selection.bonds||[])];if(!atoms.length&&!bonds.length)throw Error(t('请先在画布中选择原子或键','Select atoms or bonds on the canvas first'));await readChanges();const before=currentHighlights(),atomSet=new Set(atoms),bondSet=new Set(bonds),next=before.map(item=>({...item,atoms:item.atoms.filter(id=>!atomSet.has(id)),bonds:item.bonds.filter(id=>!bondSet.has(id))})).filter(item=>item.atoms.length||item.bonds.length);if(encode(before)===encode(next))return;pushHistory(project);applyHighlights(next);render();await persist();toast(t('已清除所选对象配色','Selected highlight colors cleared'));}
function agentHighlightTarget(highlight){if(!highlight||!['selection','all','ids'].includes(highlight.target))throw Error('Agent 返回的配色目标无效');const struct=engine?.editor?.struct(),validAtoms=new Set(ids(struct?.atoms)),validBonds=new Set(ids(struct?.bonds));let atoms,bonds;if(highlight.target==='all'){atoms=[...validAtoms];bonds=[...validBonds];}else if(highlight.target==='selection'&&!highlight.atoms?.length&&!highlight.bonds?.length)({atoms,bonds}=highlightSelection());else{atoms=[...new Set(highlight.atoms||[])];bonds=[...new Set(highlight.bonds||[])];}if(!atoms.length&&!bonds.length)throw Error('Agent 配色方案没有包含任何原子或键');if(atoms.some(id=>!validAtoms.has(id))||bonds.some(id=>!validBonds.has(id)))throw Error('Agent 配色方案包含画布中不存在的对象');return {atoms,bonds};}
function agentSelection(){try{const ed=engine?.editor,selection=ed?.selection?.();if(!selection)return null;const atomIds=ids(selection.atoms),bondIds=ids(selection.bonds),textIds=ids(selection.texts),arrowIds=ids(selection.rxnArrows);if(!atomIds.length&&!bondIds.length&&!textIds.length&&!arrowIds.length)return null;const struct=ed.struct(),out={atoms:[],bonds:[],texts:[],arrows:[]};for(const id of atomIds.slice(0,200)){const a=struct.atoms?.get(id),p=vec(a?.pp);if(p)out.atoms.push({id,location:p,label:String(a?.label||'')});}for(const id of bondIds.slice(0,200)){const b=struct.bonds?.get(id),from=vec(struct.atoms?.get(b?.begin)?.pp),to=vec(struct.atoms?.get(b?.end)?.pp);if(from&&to)out.bonds.push({id,from,to});}for(const id of textIds.slice(0,50)){const item=struct.texts?.get(id),location=vec(item?.position||item?.pp);if(location)out.texts.push({id,location});}for(const id of arrowIds.slice(0,50)){const item=struct.rxnArrows?.get(id),points=agentArrowPoints(item),from=vec(points[0]),to=vec(points[1]);if(from&&to)out.arrows.push({id,from,to});}return out.atoms.length||out.bonds.length||out.texts.length||out.arrows.length?out:null;}catch{return null;}}
function agentStructureMap(){try{const struct=engine?.editor?.struct(),atoms=[],bonds=[],texts=[],arrows=[];for(const id of ids(struct?.atoms).slice(0,5000)){const atom=struct.atoms.get(id),location=vec(atom?.pp);if(location)atoms.push({id,location,label:String(atom?.label||'')});}for(const id of ids(struct?.bonds).slice(0,7500)){const bond=struct.bonds.get(id),from=vec(struct.atoms?.get(bond?.begin)?.pp),to=vec(struct.atoms?.get(bond?.end)?.pp);if(from&&to)bonds.push({id,begin:bond.begin,end:bond.end,from,to});}for(const id of ids(struct?.texts).slice(0,1000)){const item=struct.texts.get(id),location=vec(item?.position||item?.pp);if(location)texts.push({id,location});}for(const id of ids(struct?.rxnArrows).slice(0,1000)){const item=struct.rxnArrows.get(id),points=agentArrowPoints(item),from=vec(points[0]),to=vec(points[1]);if(from&&to)arrows.push({id,from,to});}return {atoms,bonds,texts,arrows};}catch{return {atoms:[],bonds:[],texts:[],arrows:[]};}}
async function agentContext(){if(!project)throw Error('当前没有打开的画布窗口，请先从底部窗口条还原一个画布');await readChanges();let smiles='';try{smiles=await engine.getSmiles();}catch{}return {name:project.name,drawingStyle:project.drawingStyle,stats:stats(project),smiles,ket:project.ket,selection:agentSelection(),structureMap:agentStructureMap(),highlights:currentHighlights()};}
async function activateDoc(id){minimized.delete(id);if(id===activeId&&project){render();await saveMeta();return;}await syncActive();const target=docs.find(d=>d.id===id);if(!target)return;suppress++;try{if(engineDocId!==id)await engine.setMolecule(target.ket,{preserveCanvasPosition:true});activeId=id;project=target;engineDocId=id;settings(target.drawingStyle);applyHighlights(target.highlights,target);engine.editor.zoomAccordingContent(engine.editor.struct());programmaticUntil=performance.now()+500;}finally{suppress--;}render();await saveMeta();}
async function minimizeActive(){if(!project)return;await syncActive();minimized.add(activeId);activeId=null;project=null;render();await saveMeta();}
async function closeDoc(id){const d=docs.find(x=>x.id===id);if(!d)return;if(d.id===activeId)await syncActive(false);const untouched=!JSON.parse(d.ket).root.nodes.length&&!d.history.length;if(!untouched&&signature(d)!==d.savedSig&&!confirm(`画布「${d.name}」尚未保存，关闭将丢失修改。确定关闭？`))return;docs=docs.filter(x=>x.id!==id);minimized.delete(id);if(engineDocId===id)engineDocId=null;if(activeId===id){activeId=null;project=null;const next=docs.find(x=>!minimized.has(x.id));if(next)await activateDoc(next.id);else render();}else render();await window.desktop.newProject(id);await saveMeta();}
async function addDoc(doc,{sync=true,restored=false}={}){if(sync)await syncActive();docs.push(doc);suppress++;try{await engine.setMolecule(doc.ket,{preserveCanvasPosition:true});const loaded=await engine.getKet();if(JSON.parse(doc.ket).root.nodes.length&&!JSON.parse(loaded).root.nodes.length)throw Error('内容未能载入主画布');doc.ket=loaded;activeId=doc.id;project=doc;engineDocId=doc.id;settings(doc.drawingStyle);applyHighlights(doc.highlights,doc);engine.editor.zoomAccordingContent(engine.editor.struct());programmaticUntil=performance.now()+500;}catch(e){docs.pop();throw e;}finally{suppress--;}render();await saveMeta();if(!restored)await persist(doc);}
async function undo(redo=false){if(!project)return;await readChanges();const from=redo?project.future:project.history,to=redo?project.history:project.future;if(!from.length)return;const next=from[from.length-1],before=projectData(project);await put(next,{remember:false});from.pop();to.push(before);render();}
$('#undo').onclick=()=>work('撤销…',()=>undo());$('#redo').onclick=()=>work('重做…',()=>undo(true));
async function save(saveAs=false){if(!project)throw Error('没有打开的窗口');await readChanges();const text=JSON.stringify(projectData(project),null,2),result=await window.desktop.save(project.id,text,project.name,saveAs);if(result){project.savedSig=signature(project);render();toast('当前画布已保存');}}
$('#save-project').onclick=()=>work('保存整个画布…',()=>save());$('#save-as').onclick=()=>work('另存项目…',()=>save(true));
$('#project-name').onchange=e=>work('更新项目名称…',async()=>{if(!project)return;await readChanges();pushHistory(project);project.name=e.target.value.trim().slice(0,200)||'Untitled Drawing';render();await persist();});
$('#new-project').onclick=()=>work('新建空白页…',async()=>{const doc=blankDoc(uniqueName('Untitled Drawing'),project?.drawingStyle||'standard');await addDoc(doc);await window.desktop.newProject(doc.id);});
$('#drawing-style').onchange=e=>work('应用绘图样式…',async()=>{if(!project)throw Error('没有打开的窗口');await readChanges();clearTimeout(timer);timer=null;pushHistory(project);suppress++;try{project.drawingStyle=e.target.value;project.page=newProject(e.target.value).page;settings();project.ket=await engine.getKet();programmaticUntil=performance.now()+500;}finally{suppress--;}render();await persist();});
$('#style-details').onclick=()=>$('#style-dialog').showModal();$('#close-style-dialog').onclick=()=>$('#style-dialog').close();$('#fit-content').onclick=()=>{if(project){engine.editor.zoomAccordingContent(engine.editor.struct());frame.focus();}};
highlightButton.onclick=()=>{updateHighlightSelection();highlightDialog.showModal();};
$('#highlight-presets').onclick=event=>{const color=event.target.closest('[data-color]')?.dataset.color;if(!color)return;$('#highlight-color').value=color;$('#highlight-color').dispatchEvent(new Event('input'));};
$('#highlight-color').oninput=event=>{$('#highlight-hex').textContent=event.target.value.toUpperCase();highlightButton.querySelector('i').style.backgroundColor=event.target.value;};
$('#highlight-apply').onclick=()=>work(t('应用画布配色…','Applying canvas color…'),async()=>{await colorSelection($('#highlight-color').value);highlightDialog.close();});
$('#highlight-clear').onclick=()=>work(t('清除画布配色…','Clearing canvas colors…'),clearHighlights);
$('#load-smiles').onclick=()=>work('添加结构…',async()=>{if(!project)throw Error('没有打开的窗口');const source=$('#smiles-input').value.trim();if(!source)return;await engine.addFragment(source);await readChanges();await persist();$('#smiles-input').value='';engine.editor.zoomAccordingContent(engine.editor.struct());});
async function loadExample(key){await syncActive();const old=JSON.parse(await window.desktop.example(key)),next=convertLegacy(old);next.drawingStyle=project?.drawingStyle||'standard';next.page=newProject(next.drawingStyle).page;next.name=uniqueName(next.name);const doc=makeDoc(next);await addDoc(doc,{sync:false});await window.desktop.newProject(doc.id);$$('[data-example]').forEach(b=>b.classList.toggle('selected',b.dataset.example===key));toast('示例已打开为新画布窗口，可直接编辑全部内容');}
$$('[data-example]').forEach(b=>b.onclick=()=>work('打开示例…',()=>loadExample(b.dataset.example)));
async function showChemDrawImport(file){importFile=prepareChemDraw(file);$('#import-name').textContent=file.name;$('#import-page').innerHTML=importFile.pages.map((p,i)=>`<option value="${i}">${t(`第 ${i+1} 页 / 共 ${importFile.pages.length} 页`,`Page ${i+1} of ${importFile.pages.length}`)}</option>`).join('');$('#import-style').value=project?.drawingStyle||'standard';$('#import-dialog').showModal();await previewImport();}
const PASTE_SELECTION_KEYS=['atoms','bonds','sgroups','rxnArrows','rxnPluses','simpleObjects','texts','multitailArrows','images'];
function structIdSnapshot(){const struct=engine.editor.struct(),snapshot={};for(const key of PASTE_SELECTION_KEYS)snapshot[key]=new Set(ids(struct?.[key]));return snapshot;}
function selectAddedObjects(before){const struct=engine.editor.struct(),selection={};for(const key of PASTE_SELECTION_KEYS){const added=ids(struct?.[key]).filter(id=>!before[key]?.has(id));if(added.length)selection[key]=added;}if(Object.values(selection).some(group=>group.length)){engine.editor.tool('select');engine.editor.selection(selection);const canvas=engine.editor.render?.paper?.canvas;canvas?.removeEventListener('mousedown',releasePastedSelection,true);canvas?.addEventListener('mousedown',releasePastedSelection,true);}return selection;}
function releasePastedSelection(event){const canvas=engine.editor.render?.paper?.canvas;if(!canvas||event.target!==canvas&&!canvas.contains(event.target))return;const selection=engine.editor.selection?.()||{};if(!Object.values(selection).some(group=>ids(group).length))return;let item=null;try{item=engine.editor.findItem(event,PASTE_SELECTION_KEYS);}catch{}if(item&&ids(selection[item.map]).includes(item.id))return;engine.editor.selection(null);}
function ketCoordinateWalk(value,visit,key=''){
  if(key==='stereoFlagPosition')return;
  if(Array.isArray(value)){if(/^(location|position|pos|begin|end|start|finish|tail|head)$/i.test(key)&&Number.isFinite(value[0])&&Number.isFinite(value[1]))visit(value);else value.forEach(item=>ketCoordinateWalk(item,visit,key));return;}
  if(!value||typeof value!=='object')return;
  if(Number.isFinite(value.x)&&Number.isFinite(value.y))visit(value);
  for(const [childKey,child]of Object.entries(value))if(!['x','y','z'].includes(childKey))ketCoordinateWalk(child,visit,childKey);
}
function ketBounds(ket){const points=[];for(const node of ket?.root?.nodes||[])ketCoordinateWalk(node?.$ref?ket[node.$ref]:node,point=>points.push(Array.isArray(point)?[point[0],point[1]]:[point.x,point.y]));if(!points.length)return null;return {minX:Math.min(...points.map(p=>p[0])),maxX:Math.max(...points.map(p=>p[0])),minY:Math.min(...points.map(p=>p[1])),maxY:Math.max(...points.map(p=>p[1]))};}
function placeKetInBlankArea(source,currentSource){
  let ket,current;try{ket=JSON.parse(source);current=JSON.parse(currentSource);}catch{return source;}
  const sourceBox=ketBounds(ket),currentBox=ketBounds(current);if(!sourceBox||!currentBox)return source;
  const dx=currentBox.maxX-sourceBox.minX+1.5,dy=(currentBox.minY+currentBox.maxY-sourceBox.minY-sourceBox.maxY)/2;
  ketCoordinateWalk(ket,point=>{if(Array.isArray(point)){point[0]+=dx;point[1]+=dy;}else{point.x+=dx;point.y+=dy;}});
  return JSON.stringify(ket);
}
async function addClipboardSource(source){if(!project)throw Error(t('没有打开的窗口，请先还原一个画布','No window is open; restore a canvas first'));const before=structIdSnapshot();await engine.addFragment(source);await readChanges();await persist();engine.editor.zoomAccordingContent(engine.editor.struct());selectAddedObjects(before);toast(t('已粘贴到空白处；当前可整体移动，点击画布后取消组合','Pasted into free space; move it as one selection, then click the canvas to edit freely'));}
async function pasteCanvasClipboard(){const file=await window.desktop.readChemDrawClipboard();if(file.kind==='unavailable')throw Error(t('剪贴板中没有可编辑的化学对象','The clipboard does not contain editable chemical objects'));if(file.kind==='ket'){await readChanges();return addClipboardSource(placeKetInBlankArea(file.content,project.ket));}if(['smiles','mol'].includes(file.kind))return addClipboardSource(file.content);const prepared=prepareChemDraw(file);if(prepared.pages.length!==1)return showChemDrawImport(file);return addClipboardSource(prepared.source(0));}
$('#open-project').onclick=()=>work('打开文件…',async()=>{await syncActive();const file=await window.desktop.open();if(!file)return;if(['cdx','cdxml'].includes(file.kind)){await showChemDrawImport(file);return;}const input=JSON.parse(file.content),next=input.version===1?convertLegacy(input):validateUnified(input);next.name=uniqueName(next.name);const doc=makeDoc(next);await addDoc(doc,{sync:false});if(input.version===1)await window.desktop.newProject(doc.id);else{await window.desktop.acceptOpen(doc.id,file.path);doc.savedSig=signature(doc);render();}if(input.version===1)toast('旧版项目已转换为新画布窗口；原始数据可从导出菜单取回');});
async function makeSvg(p=project){if(!p)throw Error('没有打开的窗口');if(!JSON.parse(p.ket).root.nodes.length)throw Error('画布为空，请先绘图');const svg=sanitizeSvg(await(await engine.generateImage(p.ket,imageStyle(p.drawingStyle))).text()),d=svgDimensions(svg),scale=isACS(p)?nativeImageScale('acs1996'):Math.min(1,(p.page.width-60)/d.w,(p.page.height-60)/d.h),w=d.w*scale,h=d.h*scale;if(w>p.page.width||h>p.page.height)throw Error('内容超过 ACS 导出页。请拆分内容，或切换常规绘图以适应页面；不会裁掉超出部分。');return pageSvg({...projectData(p),objects:[{id:'whole-page',type:'molecule',name:p.name,ket:p.ket,svg,x:(p.page.width-w)/2,y:(p.page.height-h)/2,w,h}]});}
async function pngData(svg){const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas'),d=svgDimensions(svg),dpi=svg.includes('width="540pt"')?600:288;canvas.width=Math.round(d.w*dpi/96);canvas.height=Math.round(d.h*dpi/96);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('PNG 生成失败');const bytes=pngWithDpi(new Uint8Array(await blob.arrayBuffer()),dpi);let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);}finally{URL.revokeObjectURL(url);}}
$('#export-menu').onclick=e=>{e.stopPropagation();$('#export-options').classList.toggle('hidden');};document.addEventListener('click',e=>{if(!e.target.closest('.dropdown'))$('#export-options').classList.add('hidden');});
$$('[data-export]').forEach(button=>button.onclick=()=>{$('#export-options').classList.add('hidden');return work('导出整个画布…',async()=>{await readChanges();if(!project)throw Error('没有打开的窗口');const kind=button.dataset.export;if(kind==='ket'){await window.desktop.exportFile({name:project.name,extension:'ket',text:project.ket});return;}const svg=await makeSvg();if(kind==='pdf')await window.desktop.exportPdf(svg,project.name,project.drawingStyle);else await window.desktop.exportFile({name:project.name,extension:kind,...kind==='png'?{base64:await pngData(svg)}:{text:svg}});toast('已导出 '+kind.toUpperCase());});});
$('#original-export').onclick=()=>{$('#export-options').classList.add('hidden');return work('导出转换前项目…',async()=>{if(project?.originalProject)await window.desktop.exportFile({name:project.name+'-转换前',extension:'chemproj',text:JSON.stringify(project.originalProject,null,2)});});};
async function previewImport(){importPreview=null;$('#import-apply').disabled=true;$('#import-page').disabled=true;$('#import-style').disabled=true;$('#import-preview').textContent='正在转换…';$('#import-summary').textContent='';$('#import-warnings').replaceChildren();await readChanges();suppress++;const oldKet=await engine.getKet();try{const index=Number($('#import-page').value),next=newProject($('#import-style').value);next.name=(importFile.name.replace(/\.(cdx|cdxml)$/i,'')+(importFile.pages.length>1?` · 第 ${index+1} 页`:'')).slice(0,200);await engine.setMolecule(importFile.source(index));next.ket=await engine.getKet();if(!JSON.parse(next.ket).root.nodes.length)throw Error('此页没有可转换内容');const report=summarizeImport(next.ket,importFile.pages[index].counts),svg=sanitizeSvg(await(await engine.generateImage(next.ket,imageStyle(next.drawingStyle))).text()),d=svgDimensions(svg),doc=new DOMParser().parseFromString(svg,'image/svg+xml');doc.documentElement.setAttribute('viewBox',`0 0 ${d.w} ${d.h}`);$('#import-preview').innerHTML=new XMLSerializer().serializeToString(doc.documentElement);const c=report.counts;$('#import-summary').textContent=`${c.molecules} 个结构 · ${c.atoms} 个原子 · ${c.bonds} 条键 · ${c.texts} 处文字 · ${c.arrows} 个箭头 · ${c.images} 张图片`;$('#import-warnings').replaceChildren(...report.warnings.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));importPreview=next;$('#import-apply').disabled=false;}catch(e){$('#import-preview').textContent='无法导入此页：'+e.message;}finally{try{await engine.setMolecule(oldKet,{preserveCanvasPosition:true});settings();}finally{suppress--;$('#import-page').disabled=false;$('#import-style').disabled=false;}}}
$('#import-page').onchange=$('#import-style').onchange=()=>work('预览导入…',previewImport);$('#import-cancel').onclick=()=>{$('#import-dialog').close();importPreview=null;};$('#import-apply').onclick=()=>work('打开所选页面…',async()=>{if(!importPreview)return;$('#import-dialog').close();importPreview.name=uniqueName(importPreview.name);const doc=makeDoc(importPreview);await addDoc(doc);await window.desktop.newProject(doc.id);importPreview=null;toast('已导入为新画布窗口，现在可以直接编辑');});
$('#import-dialog').addEventListener('close',()=>{if(project)applyHighlights(project.highlights);});
$('#help').onclick=async()=>{$('#help-dialog').showModal();$('#notices').textContent=await window.desktop.notices();};$('#close-help').onclick=()=>$('#help-dialog').close();
function shortcut(e){
  const mod=e.ctrlKey||e.metaKey;if(!mod||e.altKey)return;
  const key=e.key.toLowerCase(),fromCanvas=e.currentTarget===frame.contentWindow,editable=e.target.closest?.('input,textarea,select,[contenteditable="true"]');
  if(fromCanvas&&['c','v'].includes(key)&&!e.shiftKey&&!busy&&!document.querySelector('dialog[open]')&&(!editable||e.target.matches?.('[data-cliparea]'))){
    e.preventDefault();e.stopImmediatePropagation();runContextAction(key==='c'?'copy':'paste',false);return;
  }
  if(!['s','z','y','o'].includes(key)||busy||document.querySelector('dialog[open]'))return;if(['z','y'].includes(key)&&e.target.closest?.('[contenteditable="true"]'))return;e.preventDefault();e.stopImmediatePropagation();if(key==='s')work('保存整个画布…',()=>save(e.shiftKey));else if(key==='o')$('#open-project').click();else work('撤销 / 重做…',()=>undo(key==='y'||e.shiftKey));
}
window.addEventListener('keydown',shortcut,true);window.desktop.onCloseRequested(async()=>{clearTimeout(timer);try{await ready;await readChanges();for(const d of docs)await persist(d);await saveMeta();await window.desktop.completeClose(true);}catch(e){error(e);await window.desktop.completeClose(confirm('画布恢复副本未保存成功，仍然关闭？'));}});
window.chemistry={ready,get engine(){return engine;},getProject:()=>project?clone(projectData(project)):null,sync:readChanges,loadProject:v=>put(v),loadExample:key=>work('打开示例…',()=>loadExample(key)),exportSvg:async()=>{await readChanges();return makeSvg();},pngData,undo:()=>undo(),redo:()=>undo(true),agentContext,applyAgentPlan,canvasShortcut:runCanvasShortcut,pasteClipboard:pasteCanvasClipboard,newDocument:async()=>{const doc=blankDoc(uniqueName('Untitled Drawing'),project?.drawingStyle||'standard');await addDoc(doc);return doc.id;},minimizeActive,activateDoc,closeDoc,state:()=>({activeId,docs:docs.map(d=>({id:d.id,name:d.name,minimized:minimized.has(d.id),dirty:signature(d)!==d.savedSig})),count:docs.length})};
window.chemistry.highlightSelection=(color,selection)=>colorSelection(color,selection);window.chemistry.clearHighlights=clearHighlights;window.chemistry.getHighlights=currentHighlights;
$('#help-dialog .help-content>p').textContent='0.7.0 · Claude 接口、按需修改批准、图片识别与可编辑化学绘图。';
await initI18n();topbar.append($('#agent-toggle'),$('.dropdown'),$('#language-toggle'),helpButton);window.addEventListener('chemistry-language-change',render);
initCanvasAgent({getContext:agentContext,applyPlan:applyAgentPlan});
(async()=>{try{await ready;suppress++;engine.editor.subscribe('change',changed);frame.contentWindow.addEventListener('keydown',shortcut,true);const style=frame.contentDocument.createElement('style');style.textContent='[data-testid="save-file-button"],[data-testid="undo"],[data-testid="redo"]{display:none!important}.structlnk-context-actions{border-top:1px solid #e2e7eb;margin-top:4px;padding-top:4px}.structlnk-context-actions button{align-items:center;background:transparent;border:0;color:#23313d;cursor:pointer;display:flex;font:13px "Segoe UI",sans-serif;gap:18px;justify-content:space-between;min-height:34px;padding:6px 12px;text-align:left;width:100%}.structlnk-context-actions button:hover:not(:disabled){background:#eef5f3}.structlnk-context-actions button:disabled{color:#aeb8bd;cursor:default}.structlnk-context-actions kbd{background:transparent;color:inherit;font:11px "Segoe UI",sans-serif}';frame.contentDocument.head.append(style);const restored=await window.desktop.recover();let restoredAny=false;if(restored){const entries=[];if(restored.meta&&Array.isArray(restored.meta.order)){for(const id of restored.meta.order){const text=restored.contents?.[id];if(typeof text==='string')entries.push({id,text});}for(const id of restored.meta.minimized||[])if(entries.some(x=>x.id===id))minimized.add(id);}else if(typeof restored.legacy==='string')entries.push({id:'legacy',text:restored.legacy});for(const entry of entries){try{const input=JSON.parse(entry.text);docs.push(makeDoc(input,{id:entry.id}));}catch(e){console.error('无法恢复文档',entry.id,e);}}if(docs.length){restoredAny=true;const wanted=restored.meta?.activeId&&!minimized.has(restored.meta.activeId)?restored.meta.activeId:docs.find(d=>!minimized.has(d.id))?.id||docs[0].id,target=docs.find(d=>d.id===wanted)||docs[0];minimized.delete(target.id);await engine.setMolecule(target.ket,{preserveCanvasPosition:true});activeId=target.id;project=target;engineDocId=target.id;settings(target.drawingStyle);}}if(!docs.length){const doc=blankDoc();docs.push(doc);await engine.setMolecule(EMPTY);doc.ket=await engine.getKet();activeId=doc.id;project=doc;engineDocId=doc.id;settings(doc.drawingStyle);}suppress--;render();$('#engine-loading').classList.add('hidden');$('#save-state').textContent=restoredAny?t('已恢复画布窗口 · 请保存项目','Canvas windows restored · please save the project'):t('直接在主画布绘图','Draw directly on the main canvas');}catch(e){suppress=0;$('#engine-loading').textContent=t('画布加载失败：','Canvas failed to load: ')+e.message;error(e);}})();
